Adding README.md
mittwald/typo3-mw-cache-widget pull request #10
Opened 2020-06-04 13:27 UTC by dermodmaster

Resolves #9

2020-06-04 17:06 UTC, martin-helmich requested changes

2020-06-04 17:06 UTC, martin-helmich commented on README.md
> +It will show how much memory is in use and how much is free.
Maybe emphasize again that this is about _APCu and OPCache_ memory usage, and NOT memory usage in general?

2020-06-04 17:06 UTC, martin-helmich commented on README.md
> +
This would be the ideal place in include a screenshot 😉

2020-06-04 17:06 UTC, martin-helmich commented on README.md
> +	 4. Select the zip file and click on **Upload!**.
Just a side note: Please remember to also document the installation via Composer when #1 is resolved.

2022-01-13 18:49 UTC, derhansen commented
Resolved with ecd28b8899d294af0c19cb704a8058a68c8908e3

2022-01-13 18:49 UTC, closed without merging