Fix/apcu memory with segments
mittwald/typo3-mw-cache-widget pull request #11
Opened 2020-06-04 13:28 UTC by dermodmaster

Resolves #4

2020-06-04 17:02 UTC, martin-helmich requested changes

2020-06-04 17:02 UTC, martin-helmich commented on ext_emconf.php
> +  'version' => '1.1.1',
Please raise the version separately (resolving the previous merge conflict 🤦 is fine, though)

2020-06-04 17:02 UTC, martin-helmich commented on Classes/Widgets/ApcuCacheWidget.php
> +            $this->sumMemory = floatval(number_format($total/1024/1024, self::decimals));
These are WAY to complicated in the first place. If all you want to do is round to two decimals, why not just use `round` with the `$precision` parameter?

    $this->usedMemory = round(($total - $apcuData["avail_mem"])/1024/1024, self::decimals);

2020-06-04 17:02 UTC, martin-helmich commented on Classes/Widgets/ApcuCacheWidget.php
> +            $total = $apcuData['num_seg']*$apcuData["seg_size"];
Unrelated to this change, but nevertheless: `apcu_sma_info()` may return `false` on certain (not really documented) conditions. Please add a check for that condition.

2020-06-04 17:02 UTC, martin-helmich commented on Classes/Widgets/ApcuCacheWidget.php
> +            $total = $apcuData['num_seg']*$apcuData["seg_size"];
Also, formatting:

```suggestion
            $total = $apcuData['num_seg'] * $apcuData['seg_size'];
```

2022-01-14 07:50 UTC, derhansen commented
Closes with 385ec1f and 65f4831

2022-01-14 07:50 UTC, closed without merging