change license from GPL3 to GPL2
mittwald/typo3-mw-cache-widget pull request #12
Opened 2020-06-04 13:28 UTC by dermodmaster

Resolves #5

2020-06-04 16:55 UTC, martin-helmich requested changes

2020-06-04 16:55 UTC, martin-helmich commented on ext_emconf.php
> +  'version' => '1.1.1',
Please raise the version number separately.

2020-06-04 16:55 UTC, martin-helmich commented on Classes/Widgets/AbstractDoughnutChartWidget.php
> + *  the Free Software Foundation; either any later version.
Is this search&replace gone wrong? The official recommended text from the license v2 reads:

```
This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.
```

2020-06-04 16:55 UTC, martin-helmich commented on Classes/Widgets/AbstractDoughnutChartWidget.php
> + *  the Free Software Foundation; either any later version.
Also, this was definitely not the original recommended license notice -- and this software is (arguably) not "part of the TYPO3 project". Did we plagiarize this license notice from somewhere else?

2020-06-04 16:55 UTC, martin-helmich commented on ext_emconf.php
> +  'version' => '1.1.1',
Also, there should also be a reference to the library in the `composer.json` file. Please change that also (or add, if not already present).

2022-01-13 18:51 UTC, derhansen commented
Closed with bb1a97c13b0721c93a28075791c3bf44711df0af

2022-01-13 18:51 UTC, closed without merging